name: Code Quality Checks

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Install dependencies
        run: npm install

      # Check for error and warnings
      
      - name: Svelte check
        run: npm run check-svelte
      
      - name: Tauri check
        run: npm run check-tauri
      
      # Check for code style
      
      - name: Svelte lint
        run: npm run lint-svelte
      
      - name: Tauri lint
        run: npm run lint-tauri